name: 🚀 New device request
description: Request a new device to be supported by HeadsetControl
labels: [device-request]
body:
- type: markdown
  attributes:
    value: |
      Thank you for your input!  
      
      **Note**: Probably only people with the same device can help to implement the protocol for it
      That is why it is a good idea to try it yourself 🚀! Take a look at the [Wiki](https://github.com/Sapd/HeadsetControl/wiki/Development).
      
      We are here to help you. You can provide WireShark logs, ask for help in Coding and open up a PR any time.
- type: textarea
  id: description
  attributes:
    label: Description
    description: Type in all details which could be useful
  validations:
    required: true
- type: input
  id: device
  attributes:
    label: Headset Name
    description: Manufacturer and name of the headset
    placeholder: ex. Corsair HS80
  validations:
    required: true
- type: textarea
  id: deviceinfo
  attributes:
    label: Device information
    description: |
        Please first determine the Vendor and ProductID of your headset (you can use `headsetcontrol --dev -- --list` to list all connected devices). 
        Then copy and paste the output of `headsetcontrol --dev -- --list --device VENDORID:DEVICEID` replacing **PASTE HERE**.
    value: |
        <details>
         <summary>Detailed Device Information</summary>
  
         ```
         PASTE HERE
         ```
  
        </details>
- type: checkboxes
  id: newdevice
  attributes:
    label: New Device Implementation Checklist
    description: Implementing a new device requires specific steps and tools (like WireShark) to capture and analyze device communications. This process typically can only be done by those who have physical access to the device.
    options:
      - label: I acknowledge that implementing a new device requires direct access to the device and familiarity with capturing and analyzing its communications. I have access to the device and am willing to contribute by capturing necessary data and/or attempting implementation.
        required: true
      - label: I have already attempted to capture device communications using WireShark or similar tools and am including my findings (successful or not) with this issue to assist in implementation efforts.
        required: false
      - label: I am seeking guidance on how to begin this process and am willing to collaborate with the community to add support for this device. I understand where to find resources (refer to the WIKI).
        required: false
